repos:
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: python
        types: [ python ]
        pass_filenames: true
        args: [
          '--in-place',
          '--remove-all-unused-imports',
          '--remove-unused-variables',
          '--remove-duplicate-keys',
        ]

      - id: black
        name: black
        entry: black
        language: python
        types: [ python ]
        pass_filenames: true
        args: [
          '--line-length=120',
          '--exclude=venv,migrations',
          '--target-version=py311',
          '--skip-string-normalization',
        ]

      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        pass_filenames: true
        args: [
          '--max-line-length=120',
          '--exclude=venv,migrations',
          '--max-complexity=8',
        ]
        additional_dependencies: [
          'flake8-annotations-complexity',
          'flake8-django',
          'flake8-builtins',
          'flake8-class-attributes-order',
          'flake8-comprehensions',
          'flake8-eradicate',
          'flake8-fixme',
          'flake8-import-order',
        ]


