repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff format
        language: python
        types: [ python ]
        pass_filenames: true
        args: []

      - id: isort
        name: isort
        entry: isort
        language: python
        types: [ python ]
        pass_filenames: true
        args: [
          '--profile=black',
          '--line-length=120',
          '--multi-line=3',
          '--trailing-comma',
        ]

      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [ python ]
        args: ['--ignore-missing-imports']

